application: smart-hutor
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  login: required
- url: /index.html
  static_files: index.html
  upload: index.html
  login: required
- url: /dev/.*
  script: main.py
  login: required
- url: .*
  script: main.py
